#!/bin/bash

echo "🔍 Running unit tests before commit..."

xcodebuild \
  -workspace IPC.xcworkspace \
  -scheme IPC \
  -destination 'platform=iOS Simulator,name=iPhone 16' \
  test

RESULT=$?

if [ $RESULT -ne 0 ]; then
  echo "❌ Tests failed. Commit aborted."
  exit 1
else
  echo "✅ Tests passed. Commiting......"
fi


